apiVersion: v1
kind: Pod
metadata:
 name: design-pod1
spec:
  containers:
  - image: vish/stress
    name: design-pod1
    resources:
      limits:
        cpu: "2"
        memory: "1024Mi"
      requests:
        cpu: "1"
        memory: "512Mi"
    args:
    - -cpus
    - "1"
    - -mem-total
    - "768Mi"
    - -mem-alloc-size
    - "256Mi"
    - -mem-alloc-sleep
    - "1s"


#Domain CPU requirements

